name: Locale Generator
on:
  push:
    paths:
      - '**.xml'
    branches: [ master ]
jobs:
  locale_gen:
    name: Generate Locales
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: sudo apt-get update -y && sudo apt-get install apt-transport-https -y
      - run: sudo sh -c 'wget -qO- https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -'
      - run: sudo sh -c 'wget -qO- https://storage.googleapis.com/download.dartlang.org/linux/debian/dart_stable.list > /etc/apt/sources.list.d/dart_stable.list'
      - run: sudo apt-get update -y
      - run: sudo apt-get install dart -y
      - run: dart bin/locale_gen.dart assets/locales lib/internal/locales
      - run: git config --global user.name "dahliaOS" && git commit -am "Generated Locales" && git push
